### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by v-moreau** [olmokramer/atom-block-cursor#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [block-cursor](https://github.com/olmokramer/atom-block-cursor) package, v0.12.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Users/vmwirius/.atom/packages/block-cursor/lib/block-cursor.coffee:34

TypeError: Cannot read property 'length' of null
  at BlockCursor.updateCursorStyleForScope (/Users/vmwirius/.atom/packages/block-cursor/lib/block-cursor.coffee:34:5)
  at BlockCursor.updateCursorStyleForScope (/Users/vmwirius/.atom/packages/block-cursor/lib/block-cursor.coffee:1:2)
  at BlockCursor.updateGlobalCursorStyle (/Users/vmwirius/.atom/packages/block-cursor/lib/block-cursor.coffee:30:8)
  at /Users/vmwirius/.atom/packages/block-cursor/lib/block-cursor.coffee:1:2
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/vmwirius/.atom/packages/block-cursor/node_modules/atom-package-config-observer/atom-package-config-observer.js:29:32
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:542:16
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:559:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:721:29)
  at Config.module.exports.Config.setRawScopedValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:758:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:218:14)
  at /Users/vmwirius/.atom/packages/typewriter/lib/run.coffee:20:23

```
### Commands

```
     -1:26.2 core:save (atom-text-editor.editor.cursor-i-beam.cursor-line-fix.is-focused)
     -0:48.1 settings-view:open (atom-text-editor.editor.cursor-i-beam.cursor-line-fix.is-focused)
     -0:31.5 core:confirm (atom-text-editor#block-cursor.primaryColorAlpha.editor.mini)
     -0:29.6 core:backspace (atom-text-editor#block-cursor.primaryColorAlpha.editor.mini)
     -0:26.4 core:confirm (atom-text-editor#block-cursor.primaryColorAlpha.editor.mini)
  4x -0:25.4 core:move-left (atom-text-editor#block-cursor.primaryColorAlpha.editor.mini)
  2x -0:24.3 core:move-right (atom-text-editor#block-cursor.primaryColorAlpha.editor.mini)
  5x -0:20.7 core:move-left (atom-text-editor#block-cursor.primaryColorAlpha.editor.mini)
     -0:03.1 core:move-right (atom-text-editor#block-cursor.primaryColorAlpha.editor.mini)
     -0:02.8 core:confirm (atom-text-editor#block-cursor.primaryColorAlpha.editor.mini)
     -0:01.6 core:close (atom-text-editor#block-cursor.primaryColorAlpha.editor.mini)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "my-package",
      "vim-mode",
      "Zen",
      "multi-cursor",
      "one-tab",
      "tree-view-background",
      "deprecation-cop",
      "spell-check"
    ],
    "themes": [
      "isotope-ui",
      "monokai"
    ],
    "projectHome": "/Users/vmwirius/Documents/Atom"
  },
  "block-cursor": {
    "primaryColor": {
      "red": 0,
      "green": 185,
      "blue": 252,
      "alpha": 1
    },
    "secondaryColor": {
      "red": 0,
      "green": 180,
      "blue": 255,
      "alpha": 0
    },
    "preview": "The quick brown fox jumps over the lazy dog",
    "cursorLineFix": true,
    "cursorType": "i-beam",
    "cursorThickness": 4,
    "primaryColorAlpha": 0.75
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.10.0
block-cursor, v0.12.0
cursor-count, v0.2.0
dash, v1.1.0
highlight-line, v0.10.1
isotope-ui, v2.1.1
language-haskell, v1.0.0
language-latex, v0.6.1
latex, v0.21.0
linter, v0.12.0
minimap, v4.7.6
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-selection, v4.2.0
monokai, v0.14.0
open-last-project, v0.4.1
pdf-view, v0.19.0
script, v2.19.0
typewriter, v0.3.2

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
I just published version 0.12.1 that should fix this issue. Please let me know if it works :)

**Comment by Wirius** [comment]
Yes your package doesn't bug anymore ! Thank you very mush, your work is awesome :)

**Comment by v-moreau** [comment]
Yes your package doesn't bug anymore ! Thank you very much, your work is awesome :)

**Comment by olmokramer** [comment]
Great! Thanks for letting me know and for the kind words :)
