### ISSUE TITLE
Failed to activate the block-cursor package (Atom 0.194 , block-cursor 0.12.2)

### ISSUE THREAD

**Issue by v3ss0n** [olmokramer/atom-block-cursor#13]
[Enter steps to reproduce below:]
1. update to atom 194
2. update to block-cursor v0.12.2
3. this error happens.

**Atom Version**: 0.195.0-ecd0444
**System**: linux 3.17.0-sabayon
**Thrown From**: [block-cursor](https://github.com/olmokramer/atom-block-cursor) package, v0.12.2
### Stack Trace

Failed to activate the block-cursor package

```
At cursorTickness is not defined

ReferenceError: cursorTickness is not defined
    at BlockCursor.prepareConfig (/home/v3ss/.atom/packages/block-cursor/lib/block-cursor.coffee:115:39)
    at BlockCursor.updateStylesheet (/home/v3ss/.atom/packages/block-cursor/lib/block-cursor.coffee:73:27)
    at BlockCursor.updateCursorStyleForScope (/home/v3ss/.atom/packages/block-cursor/lib/block-cursor.coffee:63:12)
    at BlockCursor.updateCursorStyleForScope (/home/v3ss/.atom/packages/block-cursor/lib/block-cursor.coffee:4:61)
    at BlockCursor.updateGlobalCursorStyle (/home/v3ss/.atom/packages/block-cursor/lib/block-cursor.coffee:49:12)
    at /home/v3ss/.atom/packages/block-cursor/lib/block-cursor.coffee:4:61
    at PackageConfigObserver.observeGlobalConfig (/home/v3ss/.atom/packages/block-cursor/node_modules/atom-package-config-observer/atom-package-config-observer.js:42:14)
    at BlockCursor.activate (/home/v3ss/.atom/packages/block-cursor/lib/block-cursor.coffee:20:27)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:222:19)
    at /opt/atom/resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:434:21)
    at /opt/atom/resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/opt/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:413:19)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-ruby-on-rails",
      "mobile-preview",
      "atom-html-preview",
      "color-picker",
      "run-command",
      "runcoderun",
      "script",
      "whitespace",
      "svg-preview",
      "autosave",
      "autocomplete-jedi",
      "autocomplete-plus-async",
      "cute-cursor",
      "pulsing-cursor",
      "neon-selection",
      "pdf-view",
      "atom-lint",
      "animation-showcase",
      "vim-mode",
      "tree-view-open-files",
      "autocomplete",
      "auto-reveal-in-sidebar",
      "ease-blink",
      "highlight-line",
      "minimap-highlight-selected",
      "tabs",
      "tree-view",
      "sublime-tabs"
    ],
    "ignoredNames": [
      "*.pyc",
      "/home/v3ss/workspace/phwa.be/condaenv",
      "/home/v3ss/workspace/phwa.be/pypyenv",
      "*.zip",
      "*.tar",
      ".hg"
    ],
    "autoHideMenuBar": true,
    "audioBeep": false,
    "themes": [
      "one-dark-pirate-ui",
      "neon-pirate"
    ]
  },
  "block-cursor": {
    "preview": "The quick brown fox jumps over the lazy dog",
    "primaryColor": {
      "red": 6,
      "green": 162,
      "blue": 255,
      "alpha": 1
    },
    "secondaryColor": {
      "red": 146,
      "green": 35,
      "blue": 35,
      "alpha": 1
    },
    "cursorThickness": 2,
    "blinkInterval": 1500,
    "pulseDuration": 1500,
    "cursorType": "bordered-box"
  }
}
```
### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.8
autocomplete-atom-api, v0.8.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.12.0
autocomplete-plus-python-jedi, v0.2.6
block-cursor, v0.12.2
build, v0.29.0
file-type-icons, v0.5.4
highlight-column, v0.4.0
highlight-selected, v0.9.2
linter, v0.12.1
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-flake8, v1.4.0
linter-jshint, v0.1.2
linter-tidy, v1.0.0
linter-xmllint, v0.0.5
local-history, v2.3.0
minimap, v4.7.6
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-selection, v4.2.0
neon-pirate, v0.3.5
one-dark-pirate-ui, v0.6.3
project-palette-finder, v2.4.16
script-runner, v1.7.3
symbols-tree-view, v0.9.2
web-browser, v1.4.4

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
Ah yes, I already received a pull request for this one. Please upgrade to `v0.12.3` :)

**Comment by v3ss0n** [comment]
ah , 0.12.3 update is not showing up in apm yet. cloning and installing from source now.

**Comment by olmokramer** [comment]
Hmm that's weird... Maybe it takes a few minutes?
