### ISSUE TITLE
Uncaught TypeError: Cannot read property 'presenter' of null

### ISSUE THREAD

**Issue by despairblue** [olmokramer/atom-block-cursor#5]
[Enter steps to reproduce below:]
1. open two panes
2. move an editor to the second pane

**Atom Version**: 0.187.0
**System**: linux 3.14.26-1-lts
**Thrown From**: [block-cursor](https://github.com/olmokramer/atom-block-cursor) package, v0.9.4
### Stack Trace

Uncaught TypeError: Cannot read property 'presenter' of null

```
At /home/despairblue/.atom/packages/block-cursor/lib/block-cursor.coffee:86

TypeError: Cannot read property 'presenter' of null
  at /home/despairblue/.atom/packages/block-cursor/lib/block-cursor.coffee:86:61
  at /usr/share/atom/resources/app/src/workspace.js:289:16
  at /usr/share/atom/resources/app/src/workspace.js:346:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app/src/pane-container.js:379:27)
  at /usr/share/atom/resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:348:20)
  at Pane.addItem (/home/despairblue/.atom/packages/tab-smart-sort/lib/tab-smart-sort.coffee:60:19)
  at Object.module.exports.swapEditor (/home/despairblue/.atom/packages/move-panes/lib/move-panes.coffee:40:12)
  at Object.module.exports.move (/home/despairblue/.atom/packages/move-panes/lib/move-panes.coffee:35:8)
  at Object.module.exports.moveRight (/home/despairblue/.atom/packages/move-panes/lib/move-panes.coffee:11:18)
  at atom-workspace.<anonymous> (/home/despairblue/.atom/packages/move-panes/lib/move-panes.coffee:4:61)
  at atom-workspace.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:246:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
  7x -1:06.6 core:move-up (atom-text-editor.editor.is-focused)
     -1:04.4 core:save (atom-text-editor.editor.is-focused)
     -0:25.3 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -0:24.7 core:close (atom-text-editor.editor.is-focused)
     -0:24.1 pane:show-item-3 (atom-text-editor.editor.is-focused)
     -0:22.7 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -0:21.8 core:close (atom-text-editor.editor.is-focused)
     -0:18.3 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:16.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:16.1 AtomPair:hide views (atom-text-editor.editor.mini)
     -0:15.8 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.block-cursor-i-beam.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:14.6 core:confirm (atom-text-editor.editor.mini)
     -0:13.9 symbols-view:toggle-file-symbols (atom-text-editor.editor)
     -0:12.7 core:confirm (atom-text-editor.editor.mini)
     -0:05.3 pane-layout:column-2 (atom-text-editor.editor)
     -0:04.7 move-panes:move-right (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "linter-scspell",
      "navigate"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "block-cursor": {
    "pulseDuration": 500,
    "primaryColor": {
      "red": 24,
      "green": 129,
      "blue": 165,
      "alpha": 1
    },
    "secondaryColor": {
      "red": 42,
      "green": 200,
      "blue": 255,
      "alpha": 1
    },
    "cursorType": "| - I-beam",
    "zzzpreview": "The quick brown fox jumps over the lazy dog"
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atom-alignment, v0.11.0
atom-beautify, v0.21.4
atom-color-highlight, v3.0.8
atom-pair, v0.37.0
atom-ternjs, v0.5.4
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.1
autocomplete-snippets, v1.0.1
block-cursor, v0.9.4
block-travel, v1.0.2
bug-report, v0.6.3
color-picker, v1.4.4
compare-files, v0.4.1
docblockr, v0.6.3
editorconfig, v0.3.0
file-icons, v1.5.1
filetype-color, v0.1.4
git-log, v0.3.0
git-plus, v4.4.8
go-plus, v3.3.0
grammar-token-limit, v0.1.1
highlight-selected, v0.9.1
indentation-indicator, v0.4.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.8
language-dockerfile, v0.1.0
language-fish-shell, v1.0.1
language-haskell, v1.0.0
language-latex, v0.4.1
language-nimrod, v0.1.0
language-puppet, v0.10.0
language-tss, v0.0.2
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-eslint, v0.4.2
linter-htmlhint, v0.0.8
linter-js-yaml, v1.0.0
linter-jshint, v0.1.0
linter-puppet-lint, v0.2.8
linter-shellcheck, v0.0.7
markdown-scroll-sync, v0.1.2
minimap, v4.5.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
move-panes, v0.1.2
open-last-project, v0.3.4
package-cop, v0.2.5
pane-layout-plus, v0.6.6
project-manager, v1.15.5
regex-railroad-diagram, v0.7.1
symbols-tree-view, v0.6.1
tab-smart-sort, v0.1.2
tabs-to-spaces, v0.8.1
test-status, v0.28.0
zentabs, v0.8.2

# Dev
atom-ternjs, v0.4.17
autocomplete-plus, v2.0.2
```

**Comment by olmokramer** [comment]
Thanks. I'll take a look at what's happening

**Comment by despairblue** [comment]
Wow, that was fast :horse_racing: :+1:

**Comment by olmokramer** [comment]
XD I was just working on the package :p

**Comment by olmokramer** [comment]
I published `v0.9.6` that should fix this issue. Does it work for you?

**Comment by despairblue** [comment]
:clap: works, thx :)

**Comment by olmokramer** [comment]
Awesome! :)

**Comment by chekhov** [comment]
But it is not working for me. It started to throw an error when I had installed open-last-project package.
