### ISSUE TITLE
Failed to activate the block-cursor package

### ISSUE THREAD

**Issue by despairblue** [olmokramer/atom-block-cursor#6]
[Enter steps to reproduce below:]
1. start atom

**Atom Version**: 0.187.0
**System**: linux 3.14.26-1-lts
**Thrown From**: [block-cursor](https://github.com/olmokramer/atom-block-cursor) package, v0.9.8
### Stack Trace

Failed to activate the block-cursor package

```
At undefined is not a function

TypeError: undefined is not a function
    at splitKeyPath (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:61:31)
    at Object.plus.valueForKeyPath (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:410:14)
    at Config.module.exports.Config.getRawValue (/usr/share/atom/resources/app/src/config.js:590:19)
    at Config.module.exports.Config.get (/usr/share/atom/resources/app/src/config.js:179:21)
    at BlockCursor.applySecondaryColor (/home/despairblue/.atom/packages/block-cursor/lib/block-cursor.coffee:111:23)
    at /home/despairblue/.atom/packages/block-cursor/lib/block-cursor.coffee:4:61
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app/src/config.js:621:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app/src/config.js:133:21)
    at BlockCursor.activate (/home/despairblue/.atom/packages/block-cursor/lib/block-cursor.coffee:84:178)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:240:19)
    at /usr/share/atom/resources/app/src/package.js:221:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:214:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:465:21)
    at /usr/share/atom/resources/app/src/package-manager.js:446:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:350:16)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "linter-scspell",
      "navigate",
      "atom-ternjs"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "block-cursor": {
    "pulseDuration": 500,
    "primaryColor": {
      "red": 24,
      "green": 129,
      "blue": 165,
      "alpha": 1
    },
    "cursorType": "| - I-beam",
    "zzzpreview": "The quick brown fox jumps over the lazy dog"
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.11.0
atom-color-highlight, v3.0.8
atom-pair, v0.37.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.2
autocomplete-snippets, v1.0.1
block-cursor, v0.9.8
block-travel, v1.0.2
bug-report, v0.6.3
color-picker, v1.4.4
compare-files, v0.4.1
docblockr, v0.6.3
file-icons, v1.5.1
filetype-color, v0.1.4
git-log, v0.3.0
go-plus, v3.3.0
grammar-token-limit, v0.1.1
highlight-selected, v0.9.1
indentation-indicator, v0.4.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.8
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-eslint, v0.4.2
linter-htmlhint, v0.0.8
linter-js-yaml, v1.0.0
linter-jshint, v0.1.0
linter-puppet-lint, v0.2.8
linter-shellcheck, v0.0.7
markdown-scroll-sync, v0.3.0
minimap, v4.6.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
open-last-project, v0.3.4
package-cop, v0.2.5
project-manager, v1.15.5
regex-railroad-diagram, v0.7.1
symbols-tree-view, v0.6.1
tab-smart-sort, v0.1.2
tabs-to-spaces, v0.8.1
test-status, v0.28.0
zentabs, v0.8.2

# Dev
autocomplete-plus, v2.0.2
```

**Comment by olmokramer** [comment]
Hmm.. Looks like an issue in Atom core. Will report to them tonight. In the meantime, you can install the old version by running `apm install block-cursor@0.9.7` so at least it will activate.

Thanks for the report.

**Comment by jeromeetienne** [comment]
thanks for your rapid reaction

**Comment by olmokramer** [comment]
I unpublished v0.9.8 from apm for now, so if you're still on that version, please reinstall the package or downgrade to v0.9.7

**Comment by olmokramer** [comment]
This should be fixed by v0.9.9

**Comment by v3ss0n** [comment]
I having this issue again on atom 194 .

**Comment by olmokramer** [comment]
@v3ss0n Can you please make a new issue with the complete stack trace of the issue? Thanks!
